model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  # target: vqgan.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: taming.main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: vqgan_data/train.txt
        size: 128
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: vqgan_data/valid.txt
        size: 128

